### ISSUE TITLE
[Commit Issue] I don't have permission to push commit on new branch

### ISSUE THREAD

**Issue by rasplarry** [aptos-labs/aptos-wallet-adapter#155]
Hello. I am developer working on [FaceWallet](https://docs.facewallet.xyz/docs) team from [Haechi Labs](https://github.com/HAECHI-LABS). 
I've made some changes to the README and the example app, and tried to push the commit(on branch named `facewallet`) to this repository.
However, I was denied permission, as shown in the error below:

```
ERROR: Permission to aptos-labs/aptos-wallet-adapter.git denied to raspLarry.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
 
How can I obtain permission to create a pull request?

**Comment by 0xmaayan** [comment]
@raspLarry You might need to fork this repo and create a pull request on the forked one. See for example this external user PR https://github.com/aptos-labs/aptos-wallet-adapter/pull/156

**Comment by rasplarry** [comment]
Thank you!
