### ISSUE TITLE
Bug: maxGasAmount not work correctly

### ISSUE THREAD

**Issue by SamuelQZQ** [aptos-labs/aptos-wallet-adapter#209]
The function `signAndSubmitTransaction` from `useWallet` declaration is: 
```
signAndSubmitTransaction(transaction: InputTransactionData, options?: InputGenerateTransactionOptions): Promise<any>;
```

Currently, it has two ways to input the `maxGasAmount`. Both of them could pass the type check but couldn't work correctly.

The first way is putting in `transaction.options`. It could pass the type check, but actually the value won't be used anywhere in the implementation. I believe we can change the first argument type of `signAndSubmitTransaction` from `InputTransactionData` to `InputGenerateTransactionData` to fix.
```
const response = await signAndSubmitTransaction({
  data: {
    function: "0x1::coin::transfer",
    typeArguments: [APTOS_COIN],
    functionArguments: [account.address, 1]
  },
  options: {
    maxGasAmount: 1000000, // here
  }
});
```

The other way to pass in `maxGasAmount` to `signAndSubmitTransaction` is putting in the second parameter `options`. It works when use Petra, but failed when using the `maxGasAmount` and using wallet Martian. It could be reproduced in the next.js example app in this repo.
```
const response = await signAndSubmitTransaction({
  data: {
    function: "0x1::coin::transfer",
    typeArguments: [APTOS_COIN],
    functionArguments: [account.address, 1], // 1 is in Octas
  },
},
{
  maxGasAmount: 1000000, // here
});
```

The error message: 
```
 Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function callback): Could not serialize message.
```

**Comment by 0xmaayan** [comment]
Thanks @SamuelQZQ , I think there are 2 issues here
1. It is not very clear how the `options` argument should be passed. After we migrated to use the new sdk, the options should be part of the argument object and not a second argument, here is a PR to fix it https://github.com/aptos-labs/aptos-wallet-adapter/pull/210
2. `maxGasAmount` is not being handled correctly on Martian wallet. I tested it with previous versions and it seems it is a wallet issue and not an adapter issue. I will surface it to Martian team to take a look at it.
