### ISSUE TITLE
React.js Deployment Issue: @aptos-labs/wallet-adapter-react Breaks After Deployment, Works Fine on Localhost

### ISSUE THREAD

**Issue by ArthurEmma2** [aptos-labs/aptos-wallet-adapter#223]
The `@aptos-labs/wallet-adapter-react` library fails to work in any React.js project during deployment, while it functions correctly on localhost.

**Steps to Reproduce:**

1. Create a new React.js project.
2. Install `@aptos-labs/wallet-adapter-react` version 2.1.4.
3. Integrate the Wallet Adapter as per the documentation.
4. Render the `Wallet` component.
5. Run the application locally.
6. Confirm proper functionality on localhost.
7. Deploy the application.
8. Observe issues in the console during deployment.

**Expected Behavior:**

Seamless integration of the wallet adapter into the React.js project on both localhost and deployment without errors.

**Actual Behavior:**

The app can't render the React.js component when the `@aptos-labs/wallet-adapter-react` is added during deployment. It works fine on localhost but breaks after deployment.

The console after deployment:
`Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at consts.ts:10:40
    at index.tsx:14:11
    at index.tsx:14:11`
    
**Environment:**

- OS: [Windows 11]

**Comment by gregnazario** [comment]
Interesting... I saw this only once with something else as well but only in one environment.

What's your version of Node and all?

**Comment by ArthurEmma2** [comment]
> Interesting... I saw this only once with something else as well but only in one environment.
> 
> What's your version of Node and all?

Node.js version: 18.18.1.
React.js verion: ^18.2.0

**Comment by gregnazario** [comment]
For now, try using 1.x.x of the wallet adapter.  Need to likely update the SDK, but I'm away from an actual computer right now

**Comment by ArthurEmma2** [comment]
> For now, try using 1.x.x of the wallet adapter. Need to likely update the SDK, but I'm away from an actual computer right now

Thanks trying it out
