### ISSUE TITLE
ModuleDependencyResolutionError: 'SimpleTransaction' not exported from '@aptos-labs/ts-sdk' after dependencies update(@aptos-labs/wallet-adapter-react)

### ISSUE THREAD

**Issue by ArthurEmma2** [aptos-labs/aptos-wallet-adapter#302]
### Issue Description
After updating to the latest versions of the Aptos wallet adapter and its dependencies, our Next application fails to compile due to a ModuleDependencyError. The error indicates that SimpleTransaction, which is expected to be exported from @aptos-labs/ts-sdk, is not found.

### Environment
Node.js version: v20.13.1
React version: ^18
Next.js version: 14.1.4
Wallet Adapter packages:
@aptos-labs/ts-sdk: ^1.9.1
@aptos-l,abs/wallet-adapter-core: ^3.3.0
@aptos-labs/wallet-adapter-react: ^3.0.3

### Steps to Reproduce
Update the following dependencies to their specified versions:
@aptos-labs/ts-sdk: ^1.9.1
@aptos-labs/wallet-adapter-core: ^3.3.0
@aptos-labs/wallet-adapter-react: ^3.0.3

### Run the application.
Observe the compilation error in the console.

### Expected Behavior
The application should compile without errors.

Actual Behavior
The application fails to compile with the following error:
`index.js:618 Uncaught ModuleDependencyError: export 'SimpleTransaction' (imported as 'SimpleTransaction') was not found in '@aptos-labs/ts-sdk' (possible exports: APTOS_BIP44_REGEX, APTOS_COIN, ...<omitted for brevity>)
`

![image](https://github.com/aptos-labs/aptos-wallet-adapter/assets/86601468/d9d0dd73-f95b-4d51-bf28-9ff6dbdfabb1)

**Comment by 0xmaayan** [comment]
please update `@aptos-labs/ts-sdk` package https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/apps/nextjs-example/package.json#L14

**Comment by ArthurEmma2** [comment]
> please update `@aptos-labs/ts-sdk` package https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/apps/nextjs-example/package.json#L14

Working now thanks
