### ISSUE TITLE
I want to abort some wallets in WalletCore, what should I do?

### ISSUE THREAD

**Issue by 0xLou1s** [aptos-labs/aptos-wallet-adapter#375]
For example, in the image below, I want to put only the Petra wallet,  i'm glad I received your help, thank you everyone.
![image](https://github.com/user-attachments/assets/7c42424b-d027-448c-a38d-570d929e934c)

**Comment by gsong** [comment]
Use `optInWallets` option: https://github.com/aptos-labs/aptos-wallet-adapter/blob/fe06a8f1dd12020e1340a3bd3a9a87114f40a446/packages/wallet-adapter-core/src/WalletCore.ts#L151

**Comment by 0xLou1s** [comment]
> Use `optInWallets` option:
> 
> https://github.com/aptos-labs/aptos-wallet-adapter/blob/fe06a8f1dd12020e1340a3bd3a9a87114f40a446/packages/wallet-adapter-core/src/WalletCore.ts#L151

I'm newbie, Can you give more details?. Thank you very much

**Comment by gsong** [comment]
See the example provided in <https://github.com/aptos-labs/aptos-wallet-adapter/tree/main/packages/wallet-adapter-react#usage>

**Comment by 0xmaayan** [comment]
Can use `optInWallets` config - note it is only valid for AIP-62 supported wallets, can find the list of these wallets [here](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/README.md#supported-wallet-packages) 
```
<AptosWalletAdapterProvider
  plugins={wallets}
  autoConnect={true}
  optInWallets={["Petra"]}
  dappConfig={{ network: network.MAINNET }}
  onError={(error) => {
    console.log("error", error);
  }}
>
  <App />
</AptosWalletAdapterProvider>;
```

**Comment by 0xLou1s** [comment]
> Can use `optInWallets` config - note it is only valid for AIP-62 supported wallets, can find the list of these wallets [here](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/README.md#supported-wallet-packages)
> 
> ```
> <AptosWalletAdapterProvider
>   plugins={wallets}
>   autoConnect={true}
>   optInWallets={["Petra"]}
>   dappConfig={{ network: network.MAINNET }}
>   onError={(error) => {
>     console.log("error", error);
>   }}
> >
>   <App />
> </AptosWalletAdapterProvider>;
> ```

tks ser, you're my hero
