### ISSUE TITLE
Is there a way to get another account that's been added to user own wallet, and connect it? like `useSwitchAccount()`

### ISSUE THREAD

**Issue by findmytrueself** [aptos-labs/aptos-wallet-adapter#390]
I am connecting to Petra wallet at web front. (I am managing personal wallet connection using `wallet-adapter-react` `useWallet()`)

Is there a way to get another account that's been added to users own wallet, and connect it? like `useSwitchAccount()`
(How to get and connect newAccount from methods such as onAccountChange in `wallet-adapter-react`)

**Comment by 0xmaayan** [comment]
Currently, the only way is to switch accounts on the web Wallet UI and then reconnect with the dapp. 

To have a `switchAccount` request coming from the dapp, a wallet would need to support an API for that - and I dont think there is a wallet in the ecosystem that  supports that
