### ISSUE TITLE
[apps/nextjs-example]: TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by LeviHHH** [aptos-labs/aptos-wallet-adapter#45]
## description
Run nextjs demo in local and got 3 errors in browser: 
```js
// error 1
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'useState')

// error 2
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'useState')

// error 3
Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```
## reproduce
browser: Chrome
pnpm version: 7.14.2
cmd:
```
pnpm install
pnpm turbo run build 
pnpm turbo run dev
```

**Comment by gregnazario** [comment]
I was having the same issue!  It is fixed with https://github.com/aptos-labs/aptos-wallet-adapter/pull/46

Please try again, and close it if it's still not working

**Comment by 0xmaayan** [comment]
Yep! just published a new version with the fix
https://github.com/aptos-labs/aptos-wallet-adapter/releases/tag/%40aptos-labs%2Fwallet-adapter-react%400.2.2

**Comment by LeviHHH** [comment]
thanks all, it works!
