### ISSUE TITLE
Show 2 confirmation popup, when connecting to the pontem wallet successfully and then switch to another account

### ISSUE THREAD

**Issue by trien-tran** [aptos-labs/aptos-wallet-adapter#53]
I test the example online [aptos-wallet-adapter ](https://aptos-labs.github.io/aptos-wallet-adapter/) , when connecting to the pontem wallet successfully and then switch to another account that has never been connected before, I see 2 confirmation popups.
 Is there any way to fix this?

**Comment by 0xmaayan** [comment]
I think this is a Pontem wallet behavior - where they expect an(y) account to approve the connection to the dapp
