### ISSUE TITLE
error: The requested module 'tweetnacl' is a CommonJS module

### ISSUE THREAD

**Issue by helloheesu** [aptos-labs/aptos-wallet-adapter#56]
Hi Aptos team,

## Error

I'm a fronend developer trying to build an Aptos dapp with Next.js.
I've installed your package and just inserted your provider in my app, and I got this error from Nextjs dev server console.

```
error - file:///rootDirectory/node_modules/@aptos-labs/wallet-adapter-core/dist/index.mjs:4
import { sign } from "tweetnacl";
         ^^^^
SyntaxError: Named export 'sign' not found. The requested module 'tweetnacl' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'tweetnacl';
const { sign } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15) {
  page: '/'
}
```

It seems lines mentions above are from your code: https://github.com/aptos-labs/aptos-wallet-adapter/blob/1c3576e466dbbcccb346d84f6f5609c8c5fa5dfd/packages/wallet-adapter-core/src/WalletCore.ts#L3-L4

## How to Reproduce

It seems the same error happens when I try to build your example app, without local package.
This is the step I tried:

1. clone `aptos-wallet-adapter` repo
2. remove `package.json`, `pnpm-lock.yaml` and `pnpm-workspace.yaml` in root directory
3. move to `apps/nextjs-example` directory
4. install packages (I tried `yarn`, but `pnpm install` should also work)
5. as there's no workspace in `example directory`'s view, `yarn` asks which version to install
6. I chose `wallet-adapter-react@0.2.2` and `wallet-adapter-ant-design@0.1.0`
7. run dev server (`yarn dev`)
8. tada - got the same error

## My code

This is how my `_app.tsx` looks like:
(in case you might need what packages I'm using, I included all import sentences as well.)

``` typescript
import { StyleProvider } from '@ant-design/cssinjs';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { AppProps } from 'next/app';
import type { NextPage } from 'next/types';
import { ReactElement, ReactNode } from 'react';
import { RecoilRoot } from 'recoil';
import { AptosWalletAdapterProvider } from '@aptos-labs/wallet-adapter-react';
import { PetraWallet } from 'petra-plugin-wallet-adapter';

const queryClient = new QueryClient();

const wallets = [new PetraWallet()];

export default function App() {
  return (
    <RecoilRoot>
      <QueryClientProvider client={queryClient}>
        <AptosWalletAdapterProvider plugins={wallets} autoConnect={true}>
          <StyleProvider hashPriority="high">
            <Component {...pageProps} />
          </StyleProvider>
        </AptosWalletAdapterProvider>
      </QueryClientProvider>
    </RecoilRoot>
  );
}
```

## Conclusion

Would you let me know if I'm doing something wrong?
My guess is the packages you're importing, such as `tweetnacl`, has something to do with this error.
I'll dig up more as well and let you know if I get something.

**Comment by 0xmaayan** [comment]
Hi, thanks for posting!

I think it is b/c of how we import the package which is not compatible with commonJS (although [tsup](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/package.json#L31) should have make this work)

looks like we need to import it like this
```
import nacl from "tweetnacl";
import { sign } from nacl;
```
