### ISSUE TITLE
[Feature Request] Add ANS support

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-labs/aptos-wallet-adapter#67]
# 🚀 Feature Request

We want to add ANS support in the wallet adapter. It means that when account is connected to the dapp, the adapter will fetch its ANS name and add it to the `account` object so the dapp can display it.

## Motivation

In the current version of the adapter, the [AccountInfo](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/src/types.ts#L14) type has account `address` and `publickKey` as mandatory properties.
```
type AccountInfo = {
  address: string;
  publicKey: string | string[];
  minKeysRequired?: number
};
```
This lets dapps the option to display the account address on the app. 
We also want to have the option to display the account ANS name.

## Pitch

To implement this feature we need Wallet to export the current connected `chainId` (so the adapter can read it and query the current ANS endpoint i.e mainnet/testnet) as part of the `network()` function response.

`chainId` is part of the Wallet Standard and currently is an optional prop in the `NetworkInfo` [type](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/src/types.ts#L8)

We want to change it to be a mandatory prop - that would be a breaking change.

Then, we would add an optional ans_name to the  `AccountInfo` type.
```
type AccountInfo = {
  address: string;
  publicKey: string | string[];
  minKeysRequired?: number;
  ansName?: string;
};
```

## Additional context
This is the list of wallets that currently **NOT** returning the `chainId` as part of the `network()` function response
Petra
Martian
TrustWallet
Spika
Fewcha
Blocto
mSafe

**Comment by borispovod** [comment]
Hey,

Sharing API endpoints can also be mandatory, as it would allow applications to use the same endpoint in case they need to do queries directly. It would allow us to don't repeat some Solana mistakes :)

**Comment by 0xmaayan** [comment]
> Hey,
> 
> Sharing API endpoints can also be mandatory, as it would allow applications to use the same endpoint in case they need to do queries directly. It would allow us to don't repeat some Solana mistakes :)

Hi! there were some discussions around that and I believe @kent-white had some thoughts on that

**Comment by kent-white** [comment]
> It would allow us to don't repeat some Solana mistakes 

Interested in the mistakes that happened?

> Sharing API endpoints can also be mandatory, as it would allow applications to use the same endpoint in case they need to do queries directly

While I think this add's some benefit to some dapp's, I think it probably bottlenecks wallets a little. Let's say I want to have a private node that user's have to have a secret token for - giving that url to the dapp wouldn't be helpful without the token.

Luckily we are using the same blockchain so whatever node wallets are using should not matter to a dapp and they should pick which node best works for their purpose. We even have a public url for most cases.

**Comment by borispovod** [comment]
Hey @kent-white,

I've been thinking about situations where the wallet endpoint and dapp endpoint can be different and, by accident, this can lead to dangerous situations such as desynchronization of data. For example, if one endpoint (used by the dapp) is not in sync, it can lead to transactions being broadcasted with outdated data, potentially resulting in financial loss. However, it is likely that the wallet endpoint would always be in sync or issues with the endpoint could be detected much earlier.

Regarding the mistakes that have happened in the past, I remember we discussed some such issues that occurred on other networks, but unfortunately, I can't find them now. The person I discussed this with is no longer in contact with me, but I will continue looking and let you know if I find anything. Even so, it seems to me that this could improve the experience for users of dapps, especially once everyone starts using different endpoints, not just the current official ones from Aptos.

**Comment by 0xmaayan** [comment]
Hi all! I think both make a lot of sense! 

> I've been thinking about situations where the wallet endpoint and dapp endpoint can be different and, by accident, this can lead to dangerous situations

@borispovod do you think handling it on the adapter level makes sense? for example, have the adapter accepts a chain_id that the dapp supports and when the wallet current network doesn't match to what the dapp expects, a message would be shown to the user. (ANS handles it in some way - try go to  https://www.aptosnames.com and have your wallet on testnet.)

@kent-white maybe that something valid that the dapp should be aware of - event though it knows the wallet current endpoint, in some use cases it might not be able to use it

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
