### ISSUE TITLE
Fix nextjs `.eslintrc.js` file

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-labs/aptos-wallet-adapter#77]
we keep having this warning on build time. 
```
ESLint: Failed to load config "adapter" to extend from. Referenced from: /home/runner/work/aptos-wallet-adapter/aptos-wallet-adapter/apps/nextjs-example/.eslintrc.js
```

This is because we try to extend `adapter` on [.eslintrc.js](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/apps/nextjs-example/.eslintrc.js) file. but we dont ave any `adapter` package.

Need to change it to extend from [eslint-config-adapter](https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/eslint-config-adapter/package.json) folder

**Comment by AnmolSirola** [comment]
@0xmaayan Can I work on this issue ?

**Comment by 0xmaayan** [comment]
> @0xmaayan Can I work on this issue ?

sure!
