### ISSUE TITLE
Add github workflow when creating a PR

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-labs/aptos-wallet-adapter#78]
Currently we have workflows running when a PR is merged https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/.github/workflows/release.yml 

We want to also have a workflow running when a PR is submitted to catch build error before merging it in.
This action should run pretty much the same steps as the existing one excluding the last step
https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/.github/workflows/release.yml#L1-L39

**Comment by AnmolSirola** [comment]
@0xmaayan Can I work on this issue :)

**Comment by 0xmaayan** [comment]
@AnmolSirola Hi, I think we already have it 😄 
https://github.com/aptos-labs/aptos-wallet-adapter/tree/main/.github/workflows
build runs on pull_request
release runs on merge into main
