### ISSUE TITLE
Update README.md for Installation Tips

### ISSUE THREAD

**Issue by hariria** [aptos-labs/aptos-wallet-adapter#93]
@0xmaayan could we add some Getting Started steps in the README.md for beginners who want to integrate with Aptos for their dApp? Maybe something like 

```
npm install @aptos-core/wallet-adapater-react
```

**Comment by 0xmaayan** [comment]
@hariria On the README.md file there is a "For Aptos Dapps" link that redirects you to the `react` package where you can find getting started steps and "how to" examples. 

Are you suggesting to move it all to the main README.md file?
