### ISSUE TITLE
signTransaction not supported for major wallets

### ISSUE THREAD

**Issue by enoch-roots** [aptos-labs/aptos-wallet-adapter#97]
Have been getting by with signAndSubmitTransaction, but wanted to separate these actions for more granular UX control and error messaging.  

Upon switching to signTransaction, have been receiving the following error

`Sign Transaction is not supported by <Petra> // <Pontem>` - for each of these wallets. 

Is signTransaction really not supported for these major wallets?  Or is this possibly a non descriptive error message?  

Any info would help, thanks!

**Comment by 0xmaayan** [comment]
looks like it is really not supported
Petra - https://www.npmjs.com/package/petra-plugin-wallet-adapter?activeTab=explore 
Pontem - https://www.npmjs.com/package/@pontem/wallet-adapter-plugin?activeTab=explore

**Comment by the-fool** [comment]
Should the interface include a `signTransaction` method?

https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/src/types.ts#L27

This addition to the API is very useful for clients that want to implement custom error handling & retry logic.

Forcing clients to use the wallet plugin to the submit the transaction is limiting in some cases.

**Comment by 0xmaayan** [comment]
Wallets need to support `signTransaction` (i.e need to implement the logic on their side) so if they don't support it the adapter has no way to support it. Can contact Petra or Pontem directly ask them why they don't support `signTransaction`.

For why it is not part of the interface, `signTransaction` most common use case would be to sign through a multi-sig wallets. In general, we should encourage to use `signAndSubmitTransaction` as it is more reliable b/c it can simulate the transaction before submitting it.

**Comment by enoch-roots** [comment]
I see, of course it is on the plugin to support, and the point on the simulator makes sense. 

On contacting petra though, is that not aptos-labs official wallet? Understand if it's just separate teams, but a disconnect between these projects' interfaces is unexpected. 

If this is an intentional design decision to suggest using signAndSubmit for the above reasons, (meaning aptos-labs own wallet plugin chooses not to support signTransaction), maybe there should be some info on this decision as it is currently listed as a feature function in the adapter docs / example on npm: https://www.npmjs.com/package/@aptos-labs/wallet-adapter-react

Anyways, not a blocker, just a quality of life wish from some devs who enjoy granular control over transaction UX. We were probably not the first, nor will be last to wonder this. Clarity on which signTx method is recommended may help all devs build out our ecosystem better & faster.   Will take this to discord for further discussion, while leaving this trail of thought here in case others are curious in the future.

Thanks for these explanations and doing great work to provide this plugin.  Excited to continue collaboration with all of these associated aptos projects.
